# docker build --build-arg MULTICAM_RELEASE=6.18.3.4935 -f Dockerfile-capture -t multicam-capture:latest .
FROM ubuntu:22.04 AS multicam-base

ARG MULTICAM_RELEASE=6.18.3.4935

RUN apt-get update && apt-get install -y apt-file file make gcc linux-headers-5.15.0-39-generic wget
COPY multicam-linux/multicam-linux-x86_64-${MULTICAM_RELEASE}.tar.gz /
RUN tar xf multicam-linux-x86_64-${MULTICAM_RELEASE}.tar.gz
WORKDIR /multicam-linux-x86_64-${MULTICAM_RELEASE}
RUN ./install.sh -m ./drivers/lib64/libMultiCam.so


FROM multicam-base AS multicam-golang

ARG GO_RELEASE=1.18.3

RUN wget https://dl.google.com/go/go${GO_RELEASE}.linux-amd64.tar.gz && \
    tar xf go${GO_RELEASE}.linux-amd64.tar.gz -C /usr/local && \
    rm go${GO_RELEASE}.linux-amd64.tar.gz
ENV PATH=${PATH}:/usr/local/go/bin
RUN go version


FROM multicam-golang AS multicam-app

COPY . /src/github.com/northvolt/go-multicam
COPY ./examples/capture/KD6R309MX_L7296RG.cam /KD6R309MX_L7296RG.cam
WORKDIR /src/github.com/northvolt/go-multicam
RUN go build -o /capture ./examples/capture/

WORKDIR /
ENTRYPOINT ["/capture"]
