// Code generated by "stringer -type MetadataContentType"; DO NOT EDIT.

package multicam

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MetadataContentNone-1]
	_ = x[MetadataContentOneField-2]
	_ = x[MetadataContentTwoField-3]
	_ = x[MetadataContentThreeField-4]
}

const _MetadataContentType_name = "MetadataContentNoneMetadataContentOneFieldMetadataContentTwoFieldMetadataContentThreeField"

var _MetadataContentType_index = [...]uint8{0, 19, 42, 65, 90}

func (i MetadataContentType) String() string {
	i -= 1
	if i < 0 || i >= MetadataContentType(len(_MetadataContentType_index)-1) {
		return "MetadataContentType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MetadataContentType_name[_MetadataContentType_index[i]:_MetadataContentType_index[i+1]]
}
