// Code generated by "stringer -type StatusCode"; DO NOT EDIT.

package multicam

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusOK-0]
	_ = x[StatusNoBoardFound - -1]
	_ = x[StatusBadParameter - -2]
	_ = x[StatusIOError - -3]
	_ = x[StatusInternalError - -4]
	_ = x[StatusNoMoreResources - -5]
	_ = x[StatusInUse - -6]
	_ = x[StatusNotSupported - -7]
	_ = x[StatusDatabaseError - -8]
	_ = x[StatusOutOfBound - -9]
	_ = x[StatusInstanceNotFound - -10]
	_ = x[StatusInvalidHandle - -11]
	_ = x[StatusTimeout - -12]
	_ = x[StatusInvalidValue - -13]
	_ = x[StatusRangeError - -14]
	_ = x[StatusBadHWConfig - -15]
	_ = x[StatusNoEvent - -16]
	_ = x[StatusLicenseNotGranted - -17]
	_ = x[StatusFatalError - -18]
	_ = x[StatusHWEventConflict - -19]
	_ = x[StatusFileNotFound - -20]
	_ = x[StatusOverflow - -21]
	_ = x[StatusInvalidParameterSetting - -22]
	_ = x[StatusParameterIllegalAccess - -23]
	_ = x[StatusClusterBusy - -24]
	_ = x[StatusServiceError - -25]
	_ = x[StatusInvalidSurface - -26]
}

const _StatusCode_name = "StatusInvalidSurfaceStatusServiceErrorStatusClusterBusyStatusParameterIllegalAccessStatusInvalidParameterSettingStatusOverflowStatusFileNotFoundStatusHWEventConflictStatusFatalErrorStatusLicenseNotGrantedStatusNoEventStatusBadHWConfigStatusRangeErrorStatusInvalidValueStatusTimeoutStatusInvalidHandleStatusInstanceNotFoundStatusOutOfBoundStatusDatabaseErrorStatusNotSupportedStatusInUseStatusNoMoreResourcesStatusInternalErrorStatusIOErrorStatusBadParameterStatusNoBoardFoundStatusOK"

var _StatusCode_index = [...]uint16{0, 20, 38, 55, 83, 112, 126, 144, 165, 181, 204, 217, 234, 250, 268, 281, 300, 322, 338, 357, 375, 386, 407, 426, 439, 457, 475, 483}

func (i StatusCode) String() string {
	i -= -26
	if i < 0 || i >= StatusCode(len(_StatusCode_index)-1) {
		return "StatusCode(" + strconv.FormatInt(int64(i+-26), 10) + ")"
	}
	return _StatusCode_name[_StatusCode_index[i]:_StatusCode_index[i+1]]
}
